"""Canonical course manifest: parts and registered modules.

This is the Source of Truth for the main app catalog and knowledge graph node list.
"""

from __future__ import annotations

from components.course_catalog import ModuleInfo
from components.course_catalog import PartInfo


PARTS: dict[str, PartInfo] = {
    "part1": PartInfo(
        "part1",
        "part1_foundations",
        "I",
        "第一部分 基础",
        "基础",
        "张量、梯度、经典机器学习、数学基础和神经网络入门。",
    ),
    "part2": PartInfo(
        "part2",
        "part2_cnn",
        "II",
        "第二部分 CNN",
        "CNN",
        "卷积、特征图、现代视觉架构、调试、迁移学习和可视化。",
    ),
    "part3": PartInfo(
        "part3",
        "part3_rnn",
        "III",
        "第三部分 RNN",
        "RNN",
        "序列建模、隐藏状态、注意力、文本分类和高级训练技巧。",
    ),
    "part4": PartInfo(
        "part4",
        "part4_transformer",
        "IV",
        "第四部分 Transformer",
        "Transformer",
        "自注意力、多头注意力、编码器解码器、生成模型和图神经网络。",
    ),
    "part5": PartInfo(
        "part5",
        "part5_toolbox",
        "V",
        "第五部分 工具箱",
        "工具箱",
        "数据训练、特征可视化、训练监控、超参搜索、部署和测验系统。",
    ),
    "part6": PartInfo(
        "part6",
        "part6_universal_framework",
        "VI",
        "第六部分 统一框架与前沿",
        "框架与前沿",
        "统一接口、模块化结构、项目模板、学习路径、术语表、AI 智能体、推理模型和前沿方向。",
    ),
    "part7": PartInfo(
        "part7",
        "part7_interview",
        "VII",
        "第七部分 CS面试八股",
        "面试八股",
        "计算机网络、数据库、数据结构、操作系统、系统设计面试训练。",
    ),
}


MODULES: list[ModuleInfo] = [
    ModuleInfo("part1", "part1_foundations", "张量与梯度", "01_tensors_gradients", "用可视化理解张量、自动求导和梯度传播。", "入门", ("基础", "张量", "梯度"), 1),
    ModuleInfo("part1", "part1_foundations", "激活与归一化", "02_activations_normalization", "比较常见激活函数、归一化方法和训练稳定性。", "入门", ("基础", "激活函数", "归一化"), 2),
    ModuleInfo("part1", "part1_foundations", "数据集与优化器", "03_datasets_optimizers", "理解数据划分、批训练、SGD、Adam 和优化曲线。", "入门", ("基础", "数据", "优化"), 3),
    ModuleInfo("part1", "part1_foundations", "数学基础速查", "math_primer", "线性代数、微积分、概率论和梯度下降的交互式速查。", "入门", ("基础", "数学", "可视化"), 4),
    ModuleInfo("part1", "part1_foundations", "机器学习基础", "machine_learning_basics", "监督学习、损失函数、泛化、评估和模型选择。", "入门", ("基础", "机器学习"), 5),
    ModuleInfo("part1", "part1_foundations", "神经网络基础", "neural_network_basics", "从感知机到多层网络，理解反向传播和非线性表达。", "入门", ("基础", "神经网络"), 6),
    ModuleInfo("part1", "part1_foundations", "经典机器学习", "classical_ml", "用传统模型建立深度学习前的基线意识。", "入门", ("基础", "模型", "基线"), 7),
    ModuleInfo("part2", "part2_cnn", "卷积直觉", "01_convolution_visual", "用滑窗、卷积核和边缘检测建立 CNN 直觉。", "进阶", ("视觉", "CNN", "卷积"), 10),
    ModuleInfo("part2", "part2_cnn", "特征图可视化", "02_feature_maps", "观察卷积层如何从局部纹理逐步形成抽象特征。", "进阶", ("视觉", "CNN", "可视化"), 11),
    ModuleInfo("part2", "part2_cnn", "经典 CNN 架构", "03_classic_architectures", "梳理 LeNet、AlexNet、VGG、GoogLeNet 和 ResNet。", "进阶", ("视觉", "CNN", "架构"), 12),
    ModuleInfo("part2", "part2_cnn", "CNN 调试面板", "04_debug_panel", "定位卷积模型训练中的过拟合、梯度和数据问题。", "工程", ("视觉", "调试", "训练"), 13),
    ModuleInfo("part2", "part2_cnn", "MNIST 玩具实验", "05_mnist_toy", "用小型手写数字实验串起数据、模型、训练和评估。", "实验", ("视觉", "CNN", "实验"), 14),
    ModuleInfo("part2", "part2_cnn", "现代 CNN 架构", "06_modern_architectures", "理解残差、深度可分离卷积和高效视觉网络。", "进阶", ("视觉", "CNN", "架构"), 15),
    ModuleInfo("part2", "part2_cnn", "高级卷积技术", "07_advanced_convolution", "扩张卷积、转置卷积、分组卷积和感受野分析。", "进阶", ("视觉", "CNN", "卷积"), 16),
    ModuleInfo("part2", "part2_cnn", "Grad-CAM 可视化", "08_visualization_gradcam", "用热力图解释 CNN 决策关注区域。", "实验", ("视觉", "解释性", "可视化"), 17),
    ModuleInfo("part2", "part2_cnn", "迁移学习", "09_transfer_learning", "复用预训练模型完成小数据任务。", "工程", ("视觉", "迁移学习"), 18),
    ModuleInfo("part2", "part2_cnn", "CNN 架构实验", "cnn_architectures", "对比经典卷积网络的结构与特征提取方式。", "进阶", ("视觉", "CNN"), 19),
    ModuleInfo("part2", "part2_cnn", "高级 CNN", "advanced_cnn", "现代卷积技巧、残差思想和视觉模型设计。", "进阶", ("视觉", "CNN"), 20),
    ModuleInfo("part3", "part3_rnn", "RNN 直觉", "01_rnn_intuition", "从循环状态理解序列信息如何流动。", "进阶", ("序列", "RNN"), 30),
    ModuleInfo("part3", "part3_rnn", "隐藏状态", "02_hidden_states", "观察隐藏状态、门控结构和长期依赖。", "进阶", ("序列", "RNN", "可视化"), 31),
    ModuleInfo("part3", "part3_rnn", "序列玩具任务", "03_sequence_toys", "用可控任务理解记忆、预测和序列泛化。", "实验", ("序列", "RNN", "实验"), 32),
    ModuleInfo("part3", "part3_rnn", "RNN 超参实验", "04_hyperparam_rnn", "比较学习率、隐藏维度、层数和截断反传。", "实验", ("序列", "训练", "超参数"), 33),
    ModuleInfo("part3", "part3_rnn", "Seq2Seq 与注意力", "05_seq2seq_attention", "理解编码器解码器和注意力对齐。", "核心", ("序列", "注意力", "NLP"), 34),
    ModuleInfo("part3", "part3_rnn", "文本分类", "06_text_classification", "用序列模型完成文本表示和分类。", "实验", ("序列", "NLP", "分类"), 35),
    ModuleInfo("part3", "part3_rnn", "高级训练技巧", "07_advanced_training", "处理梯度裁剪、Teacher Forcing、正则化和训练稳定性。", "工程", ("序列", "训练", "调试"), 36),
    ModuleInfo("part3", "part3_rnn", "RNN 调试问题", "08_debug_problems", "定位序列模型中的梯度、数据和评估问题。", "工程", ("序列", "调试"), 37),
    ModuleInfo("part3", "part3_rnn", "序列模型", "sequence_models", "RNN、LSTM、GRU 与序列任务的基本范式。", "进阶", ("序列", "NLP"), 38),
    ModuleInfo("part4", "part4_transformer", "注意力机制", "01_attention_mechanism", "从查询、键、值理解注意力权重。", "核心", ("Transformer", "注意力"), 40),
    ModuleInfo("part4", "part4_transformer", "多头注意力可视化", "02_multihead_visual", "观察不同注意力头如何捕获互补关系。", "核心", ("Transformer", "注意力", "可视化"), 41),
    ModuleInfo("part4", "part4_transformer", "编码器与解码器", "03_encoder_decoder", "拆解 Transformer 编码器、解码器和掩码机制。", "核心", ("Transformer", "NLP"), 42),
    ModuleInfo("part4", "part4_transformer", "最小 Transformer", "04_minimal_transformer", "用精简实现串起嵌入、注意力、MLP 和残差。", "核心", ("Transformer", "实现"), 43),
    ModuleInfo("part4", "part4_transformer", "Flash Attention", "05_flash_attention", "理解高效注意力的内存访问与计算优化。", "前沿", ("Transformer", "性能", "注意力"), 44),
    ModuleInfo("part4", "part4_transformer", "Transformer 调试", "06_debug_problems", "分析大模型训练中的掩码、位置编码和梯度问题。", "工程", ("Transformer", "调试"), 45),
    ModuleInfo("part4", "part4_transformer", "Transformer 架构", "transformer_models", "可视化拆解自注意力、多头、位置编码和 BERT/GPT。", "核心", ("Transformer", "NLP"), 46),
    ModuleInfo("part4", "part4_transformer", "GAN 与自编码器", "gan_ae", "理解生成模型、潜空间和重构学习。", "进阶", ("生成模型", "表征"), 47),
    ModuleInfo("part4", "part4_transformer", "图神经网络", "gnn_intro", "从节点、边和消息传递理解图学习。", "进阶", ("GNN", "结构数据"), 48),
    ModuleInfo("part5", "part5_toolbox", "特征可视化", "01_feature_visualization", "观察特征、激活、嵌入和决策边界。", "工程", ("工具", "可视化", "解释性"), 50),
    ModuleInfo("part5", "part5_toolbox", "梯度监控", "02_gradient_monitor", "监控梯度范数、爆炸、消失和训练健康度。", "工程", ("工具", "梯度", "调试"), 51),
    ModuleInfo("part5", "part5_toolbox", "训练动态", "03_training_dynamics", "用曲线和指标追踪模型如何学习。", "工程", ("训练", "监控"), 52),
    ModuleInfo("part5", "part5_toolbox", "超参搜索", "04_hyperparam_search", "比较网格搜索、随机搜索和实验记录。", "工程", ("超参数", "工具"), 53),
    ModuleInfo("part5", "part5_toolbox", "玩具数据集", "05_dataset_toys", "用小数据集快速验证模型直觉。", "实验", ("数据", "实验"), 54),
    ModuleInfo("part5", "part5_toolbox", "数据与训练", "data_training", "数据管线、训练循环、指标与调试。", "工程", ("训练", "数据"), 55),
    ModuleInfo("part5", "part5_toolbox", "案例研究", "case_studies", "用完整案例串联建模、调参和诊断流程。", "工程", ("案例", "实践"), 56),
    ModuleInfo("part5", "part5_toolbox", "部署工具", "deployment_tools", "模型导出、服务化、推理和工程落地。", "工程", ("部署", "工具"), 57),
    ModuleInfo("part5", "part5_toolbox", "练习题与测验", "quiz_system", "覆盖机器学习基础、CNN、RNN、Transformer 和 GAN 的交互式测验。", "复习", ("测验", "复习"), 58),
    ModuleInfo("part5", "part5_toolbox", "调参实战挑战", "tuning_challenge", "在真实约束下练习学习率、正则、模型规模和实验记录决策。", "实验", ("调参", "实验", "诊断"), 59),
    ModuleInfo("part6", "part6_universal_framework", "统一接口", "01_unified_interface", "把模型、数据和任务抽象成统一可扩展接口。", "工程", ("框架", "架构"), 60),
    ModuleInfo("part6", "part6_universal_framework", "模块化结构", "02_modular_structure", "拆分配置、数据、模型、训练和评估边界。", "工程", ("框架", "模块化"), 61),
    ModuleInfo("part6", "part6_universal_framework", "完整项目骨架", "03_full_project", "组织可复用的深度学习项目目录和执行流程。", "工程", ("项目", "架构"), 62),
    ModuleInfo("part6", "part6_universal_framework", "插件系统", "04_plugin_system", "用注册表和插件扩展任务、模型与工具。", "工程", ("框架", "插件"), 63),
    ModuleInfo("part6", "part6_universal_framework", "一键训练", "05_one_click_training", "从配置到训练、评估和产物保存的一键流程。", "工程", ("训练", "自动化"), 64),
    ModuleInfo("part6", "part6_universal_framework", "可视化实验台", "06_streamlit_demo", "用 Streamlit 交互观察边界、卷积和注意力。", "核心", ("实验", "可视化", "Streamlit"), 65),
    ModuleInfo("part6", "part6_universal_framework", "神经网络乐高工厂", "neural_network_playground", "用表单构建神经网络、形状推导、代码生成、示例模型加载。", "核心", ("构建器", "Playground", "实战"), 66),
    ModuleInfo("part6", "part6_universal_framework", "训练过程可视化", "training_demo", "用轻量数据集演示训练循环，实时展示损失、准确率、梯度范数。标注教学演示。", "核心", ("训练", "可视化", "演示"), 67),
    ModuleInfo("part6", "part6_universal_framework", "项目模板", "07_project_template", "训练脚本、评估脚本、K-Fold 和集成预测模板。", "工程", ("项目", "模板"), 66),
    ModuleInfo("part6", "part6_universal_framework", "强化学习入门", "reinforcement_learning", "强化学习概念、多臂老虎机、Q-Learning 和纯 Python 环境 demo。", "核心", ("RL", "强化学习", "实验"), 67),
    ModuleInfo("part6", "part6_universal_framework", "学习路径推荐", "learning_path", "入门测评、个性化路径、知识图谱、进度追踪和下一步推荐。", "核心", ("路径", "知识图谱", "测评"), 68),
    ModuleInfo("part6", "part6_universal_framework", "深度学习术语表", "glossary", "集中检索常见概念、缩写和相关模块。", "复习", ("术语", "搜索", "复习"), 69),
    ModuleInfo("part6", "part6_universal_framework", "前沿方向", "frontier", "LLM、AGI、多模态、AI 智能体、推理模型、自监督、XAI、安全与对齐。", "前沿", ("LLM", "AGI", "Agents", "安全"), 70),
    ModuleInfo("part6", "part6_universal_framework", "经典论文解读实验室", "paper_reading_lab", "用时间线、机制图和最小复现清单读懂经典深度学习论文。", "进阶", ("论文", "可视化", "复现"), 71),
    ModuleInfo("part7", "part7_interview", "计算机网络", "networking", "TCP握手挥手、HTTP/HTTPS、DNS解析、高频面试题与交互练习。", "核心", ("网络", "TCP", "HTTP", "面试"), 70),
    ModuleInfo("part7", "part7_interview", "数据库SQL", "database_sql", "SELECT执行流程、B+树索引、慢查询排查、高频面试题与交互练习。", "核心", ("数据库", "SQL", "索引", "面试"), 71),
    ModuleInfo("part7", "part7_interview", "数据结构与算法", "data_structures", "数组链表可视化、排序算法动画、BFS/DFS、高频面试题。", "核心", ("数据结构", "算法", "排序", "面试"), 72),
    ModuleInfo("part7", "part7_interview", "操作系统", "operating_system", "进程线程、调度算法、虚拟内存、死锁、高频面试题。", "核心", ("操作系统", "进程", "内存", "面试"), 73),
    ModuleInfo("part7", "part7_interview", "系统设计", "system_design", "CAP定理、缓存三兄弟、消息队列、推荐架构、分布式训练、推理平台设计与交互练习。", "核心", ("系统设计", "架构", "面试", "分布式"), 73),
    ModuleInfo("part7", "part7_interview", "深度学习", "deep_learning_interview", "梯度消失可视化、BatchNorm vs LayerNorm、注意力复杂度、训练排查清单、LoRA微调、模型部署。", "核心", ("深度学习", "梯度", "归一化", "面试"), 74),
    ModuleInfo("part7", "part7_interview", "自测刷题模式", "interview_quiz", "随机出题、按方向难度筛选、错题本、延伸追问。", "核心", ("刷题", "自测", "错题本"), 75),
]

REGISTERED_MODULES: tuple[ModuleInfo, ...] = tuple(MODULES)
